/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/fbnz9fMzazW
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { DM_Serif_Display } from 'next/font/google'

dm_serif_display({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Button } from "@/components/ui/button"
import Link from "next/link"
import { Avatar, AvatarImage, AvatarFallback } from "@/components/ui/avatar"

export function Theme1() {
  return (
    (<div
      className="grid grid-cols-1 md:grid-cols-[3fr_1fr] gap-8 px-4 md:px-6 py-8 md:py-12">
      <div className="space-y-8">
        <div className="grid gap-6">
          <div className="grid gap-2">
            <h1 className="text-3xl font-bold">Latest Blog Posts</h1>
            <p className="text-muted-foreground">Discover the latest insights and trends in our blog.</p>
          </div>
          <div className="grid gap-6">
            <div className="grid md:grid-cols-[200px_1fr] gap-6">
              <img
                src="/placeholder.svg"
                width={200}
                height={150}
                alt="Blog post cover"
                className="rounded-lg object-cover" />
              <div className="space-y-2">
                <h2 className="text-xl font-semibold">The Future of Remote Work: Trends and Insights</h2>
                <div className="flex items-center gap-2 text-muted-foreground">
                  <div className="flex items-center gap-1">
                    <UserIcon className="w-4 h-4" />
                    <span>John Doe</span>
                  </div>
                  <div className="flex items-center gap-1">
                    <CalendarIcon className="w-4 h-4" />
                    <span>May 15, 2023</span>
                  </div>
                </div>
                <p className="text-muted-foreground line-clamp-3">
                  As the world continues to adapt to the new normal, the landscape of work has undergone a significant
                  transformation. Remote work, once a niche concept, has become the norm for many organizations,
                  ushering in a new era of flexibility, productivity, and work-life balance.
                </p>
              </div>
            </div>
            <div className="grid md:grid-cols-[200px_1fr] gap-6">
              <img
                src="/placeholder.svg"
                width={200}
                height={150}
                alt="Blog post cover"
                className="rounded-lg object-cover" />
              <div className="space-y-2">
                <h2 className="text-xl font-semibold">
                  Unlocking the Power of Data: A Guide to Effective Data Analysis
                </h2>
                <div className="flex items-center gap-2 text-muted-foreground">
                  <div className="flex items-center gap-1">
                    <UserIcon className="w-4 h-4" />
                    <span>Jane Smith</span>
                  </div>
                  <div className="flex items-center gap-1">
                    <CalendarIcon className="w-4 h-4" />
                    <span>April 28, 2023</span>
                  </div>
                </div>
                <p className="text-muted-foreground line-clamp-3">
                  In today's data-driven world, the ability to effectively analyze and interpret information has become
                  a crucial skill. Whether you're a business owner, a marketing professional, or a data enthusiast,
                  understanding how to harness the power of data can unlock valuable insights and drive informed
                  decision-making.
                </p>
              </div>
            </div>
            <div className="grid md:grid-cols-[200px_1fr] gap-6">
              <img
                src="/placeholder.svg"
                width={200}
                height={150}
                alt="Blog post cover"
                className="rounded-lg object-cover" />
              <div className="space-y-2">
                <h2 className="text-xl font-semibold">Sustainable Living: Practical Tips for a Greener Lifestyle</h2>
                <div className="flex items-center gap-2 text-muted-foreground">
                  <div className="flex items-center gap-1">
                    <UserIcon className="w-4 h-4" />
                    <span>Sarah Lee</span>
                  </div>
                  <div className="flex items-center gap-1">
                    <CalendarIcon className="w-4 h-4" />
                    <span>March 12, 2023</span>
                  </div>
                </div>
                <p className="text-muted-foreground line-clamp-3">
                  In a world facing the challenges of climate change and environmental degradation, the need for
                  sustainable living has never been more pressing. From reducing our carbon footprint to adopting
                  eco-friendly habits, there are numerous ways we can contribute to a greener future.
                </p>
              </div>
            </div>
          </div>
        </div>
        <div className="grid gap-6">
          <div className="grid gap-2">
            <h2 className="text-2xl font-bold">Load More</h2>
            <p className="text-muted-foreground">Explore more blog posts and stay up-to-date with the latest trends.</p>
          </div>
          <Button className="w-full">Load More</Button>
        </div>
      </div>
      <div className="space-y-8">
        <div className="grid gap-4">
          <h2 className="text-2xl font-bold">Trending Posts</h2>
          <div className="grid gap-2">
            <Link
              href="#"
              className="flex items-center gap-2 text-muted-foreground hover:text-primary transition-colors"
              prefetch={false}>
              <FileTextIcon className="w-4 h-4" />
              <span className="line-clamp-1">The Future of Remote Work: Trends and Insights</span>
            </Link>
            <Link
              href="#"
              className="flex items-center gap-2 text-muted-foreground hover:text-primary transition-colors"
              prefetch={false}>
              <FileTextIcon className="w-4 h-4" />
              <span className="line-clamp-1">Unlocking the Power of Data: A Guide to Effective Data Analysis</span>
            </Link>
            <Link
              href="#"
              className="flex items-center gap-2 text-muted-foreground hover:text-primary transition-colors"
              prefetch={false}>
              <FileTextIcon className="w-4 h-4" />
              <span className="line-clamp-1">Sustainable Living: Practical Tips for a Greener Lifestyle</span>
            </Link>
          </div>
        </div>
        <div className="grid gap-4">
          <h2 className="text-2xl font-bold">Trending Users</h2>
          <div className="grid grid-cols-4 gap-4">
            <Link
              href="#"
              className="flex flex-col items-center gap-2 text-muted-foreground hover:text-primary transition-colors"
              prefetch={false}>
              <Avatar className="w-12 h-12 border">
                <AvatarImage src="/placeholder-user.jpg" />
                <AvatarFallback>JD</AvatarFallback>
              </Avatar>
              <span className="line-clamp-1">John Doe</span>
            </Link>
            <Link
              href="#"
              className="flex flex-col items-center gap-2 text-muted-foreground hover:text-primary transition-colors"
              prefetch={false}>
              <Avatar className="w-12 h-12 border">
                <AvatarImage src="/placeholder-user.jpg" />
                <AvatarFallback>JS</AvatarFallback>
              </Avatar>
              <span className="line-clamp-1">Jane Smith</span>
            </Link>
            <Link
              href="#"
              className="flex flex-col items-center gap-2 text-muted-foreground hover:text-primary transition-colors"
              prefetch={false}>
              <Avatar className="w-12 h-12 border">
                <AvatarImage src="/placeholder-user.jpg" />
                <AvatarFallback>SL</AvatarFallback>
              </Avatar>
              <span className="line-clamp-1">Sarah Lee</span>
            </Link>
            <Link
              href="#"
              className="flex flex-col items-center gap-2 text-muted-foreground hover:text-primary transition-colors"
              prefetch={false}>
              <Avatar className="w-12 h-12 border">
                <AvatarImage src="/placeholder-user.jpg" />
                <AvatarFallback>MJ</AvatarFallback>
              </Avatar>
              <span className="line-clamp-1">Michael Johnson</span>
            </Link>
          </div>
        </div>
      </div>
    </div>)
  );
}

function CalendarIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <path d="M8 2v4" />
      <path d="M16 2v4" />
      <rect width="18" height="18" x="3" y="4" rx="2" />
      <path d="M3 10h18" />
    </svg>)
  );
}


function FileTextIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <path d="M15 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V7Z" />
      <path d="M14 2v4a2 2 0 0 0 2 2h4" />
      <path d="M10 9H8" />
      <path d="M16 13H8" />
      <path d="M16 17H8" />
    </svg>)
  );
}


function UserIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <path d="M19 21v-2a4 4 0 0 0-4-4H9a4 4 0 0 0-4 4v2" />
      <circle cx="12" cy="7" r="4" />
    </svg>)
  );
}
